spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/roles-chat-ai?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000
  application:
    name: chat-service
  ai:
    dashscope:
      api-key: "sk-5c632b3144464e588655b80556cafd28"
      chat:
        options:
          model: qwen-plus
  cloud:
    nacos:
      server-addr: 1.15.105.45:8848
      username: nacos
      password: 123456
      discovery:
        group: QUIZ_GROUP
        enabled: true
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 20000ms
server:
  port: 8083
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blueberry.quiz_question.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.blueberry.quiz_question.controller
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos:1.15.105.45:8848
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.example.provider.service
knife4j:
  enable: true
  setting:
    language: zh_cn